---
- hosts: Fedora 
  become: true
  tasks:
   - name: Install Common Packages and Dependencies 
     dnf:
        name: wget, alsa-lib, pulseaudio, glibc, unrar, unzip, p7zip, p7zip-plugins 
        state: latest
